### ISSUE TITLE
Suggestion - toggle to hide

### ISSUE THREAD

**Issue by steve2116** [Mezeman1/idle-ant-farm#10]
Some prestige upgrades you buy once and don't buy again (auto features). It would be nice to be able to hide them. At the moment it's just that one collapsible section, but in the future it might be more.

Also some inventory items cannot be used. Similarly if we could toggle to hide them too that would be nice. Or show only them - but that's getting more into a filter than a toggle

**Comment by Mezeman1** [comment]
Good suggestion!
