### ISSUE TITLE
Buggy "Start/Stop Battle" button

### ISSUE THREAD

**Issue by steve2116** [Mezeman1/idle-ant-farm#11]
(pun intended)

I'm not able to reliably reproduce this issue, but sometimes the button shows "Start Battle" when the army is already battling. Sometimes the reverse too.

It mostly happens (just from memory) whenever I go to a different tab while battling, and then when I next go back to the adventure tab it would show "Start Battle" while still battling. And then if I click to battle it would show "Stop Battle" while the army would not be battling.

I'm on ios 16.5.1, google chrome 128.0.6613.92 (I don't know if they'll help 🤷‍♂️)

**Comment by Mezeman1** [comment]
I think I fixed this today actually

**Comment by steve2116** [comment]
Seems to be fixed. I can't replicate it from a small amount of testing 👍
