### ISSUE TITLE
Game freezes whenever clicking on buy max ants or enabling autobuy

### ISSUE THREAD

**Issue by bitdevv** [Mezeman1/idle-ant-farm#17]
I have quite big numbers also, might be the cause
![image](https://github.com/user-attachments/assets/315cb52c-a5ba-482a-826a-d08e30e5fcf1)

**Comment by Mezeman1** [comment]
I've not been able to get numbers like these yet. You should probably try a hard reset in de settings and play from there. It's much more balanced. But I'll definitely look into it!

**Comment by githuubium** [comment]
When buying like 20k ants the game is freezing for good 5-10 seconds
