### ISSUE TITLE
10 ants or 2 queens not unlocking battle wasteland

### ISSUE THREAD

**Issue by MercuriusXeno** [Mezeman1/idle-ant-farm#18]
Seems after the resource refactor the battle areas aren't unlocking.
Repro steps:
1. wipe save
2. accumulate 10 ants (or 2 queens or both)
3. observe adventure dropdown still has wasteland locked

**Comment by Mezeman1** [comment]
Thank you, I did a big refactor of the resources, but forgot to refactor the enemy waves. Fixed!

**Comment by MercuriusXeno** [comment]
Your commit history is bananas. Good job on the game so far.

**Comment by Mezeman1** [comment]
Haha, what do you mean? How much I commit?
I'm just pushing as many features as possible. And honestly, enjoying it so much, especially with all the feedback I'm getting.
