### ISSUE TITLE
Just started my new game and on second prestige, this looks wrong...

### ISSUE THREAD

**Issue by ArthurHawk92** [Mezeman1/idle-ant-farm#19]
![Screenshot_2024-09-13-13-03-10-69_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/c36a2bf2-ac44-40aa-b28e-2fe450c6f0c1)
![Screenshot_2024-09-13-13-08-04-46_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/034adc78-2d34-4cf0-a05d-a8ac2e0b4bc8)
![Screenshot_2024-09-13-13-08-19-06_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/1e8faa23-b55e-4f37-a1ed-8c7566945e9a)

Not entirely sure what happened, what I do know is I only prestiged twice and only upgraded twice, and this run have bought no upgrades, but clearly I shouldn't have started with that much storage that round, and I have 0 ants but it's going up as if I still have 200 ants, also it went from 200 obtainable ants to 800 from a single prestige?

**Comment by ArthurHawk92** [comment]
What I do think happened is maybe I spammed the button for buying the storage upgrade in prestige and it counted under ants but never counted as another prestige. 
Also I think it's cause the storage for the seeds was still filling up when I prestiged that it carried on filling and left me with 60k+ storage.

I will try to repeat it to see what happens.

**Comment by ArthurHawk92** [comment]
Tried repeating and just prestiging 4x my ants queens etc... so basically it's reusing the storage upgrades that I had before I prestiged, and yes if you prestige well seed storage is filling it will continue to fill after prestige.

**Comment by ArthurHawk92** [comment]
![Screenshot_2024-09-13-13-23-46-80_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/53b7657e-e2b7-43bd-a907-be9a13015e9e)
![Screenshot_2024-09-13-13-23-52-17_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/90a331bf-2696-4eac-a972-a7e4739d2674)
![Screenshot_2024-09-13-13-23-59-84_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/f71137f7-9816-4d78-bf3a-25b638e20be4)

**Comment by Mezeman1** [comment]
Thanks for finding this! Resolved
