### ISSUE TITLE
miscolored text on hover

### ISSUE THREAD

**Issue by TheInterester-school** [Mezeman1/idle-ant-farm#21]
the text for the first locked upgrade is briefly colored the yellow of the upgrade seed storage button when hovering over it. this is the text that says "maybe how many times we prestiged?".

**Comment by Mezeman1** [comment]
Can't reproduce, care to show a picture or video?

**Comment by TheInterester-school** [comment]
i can't reproduce it either anymore. it must have been a really specific window size. if i end up recreating it i'll record

**Comment by Mezeman1** [comment]
Thankyou! Will close for now.
