### ISSUE TITLE
Game will revert to previous save when going into offline time when you tab out.

### ISSUE THREAD

**Issue by hugojmaia** [Mezeman1/idle-ant-farm#27]
Basically when I tab out the game will revert to last time it saved when returning to the tab.
Can be remedied if I remember to click the manual save button before tabbing out, but it's an annoying.

**Comment by Mezeman1** [comment]
On hide, I will save, on show, I will load again and start the gameloop. I've implemented that now. Would love it if you could test!

**Comment by hugojmaia** [comment]
Thanks, it's functioning good now.
