### ISSUE TITLE
Change the threshold for auto-buy queens.

### ISSUE THREAD

**Issue by hugojmaia** [Mezeman1/idle-ant-farm#28]
Currently it's set to buy asap, so it can completely murder progress when you go from 50 ants to 0 cause the autobuyer did its thing.
The ability to set it to something like "Only buy queens if ants > 300" would help in this regard.

**Comment by Mezeman1** [comment]
For now, only autobuying when ants storage is half full.

Will implement thresholds in settings later.

**Comment by Mezeman1** [comment]
Implemented
