### ISSUE TITLE
Make the Create Housing upgrade more meaningful.

### ISSUE THREAD

**Issue by hugojmaia** [Mezeman1/idle-ant-farm#29]
Currently the Create Housing upgrade is +1 max ant per upgrade and increases the cost by 1 seed per upgrade bought.
This upgrade could use scaling similar to the Upgrade Storage for seeds and larvae. Both for cost and amount of max units provided.

**Comment by Mezeman1** [comment]
Reason I did not do that is pretty simple.

Balancing issues.

Once I do what you suggest here. The gameloop would go too fast.
