### ISSUE TITLE
Items on mobile

### ISSUE THREAD

**Issue by steve2116** [Mezeman1/idle-ant-farm#3]
To be able to see what items do, I need to click on them. Clicking on them uses them.

-> If I want to see what the items do, I need to use them. And if I use them, I only see what the item does if I have more than one (but I would still have to use one of the items each click to be able to see the info box)

Maybe a if-statement or something to check that the info box is showing before letting the click on the item count as using the item

**Comment by Mezeman1** [comment]
Thanks for the feedback, plan is, to click item, and show detail, where you can click use etc.
But it's so early in development I've not had the time to play with that yet.

**Comment by Mezeman1** [comment]
Resolved, planning to make the ui better later.
