### ISSUE TITLE
Save auto states between refreshes

### ISSUE THREAD

**Issue by steve2116** [Mezeman1/idle-ant-farm#31]
I turn auto queen buy off, I refresh it is back on.

I think either saving between refreshes and/or in save file (even tabbing out and back in resets it) would be good. But also just having them default to off would work.

**Comment by Mezeman1** [comment]
The thing is, that on refresh, there's not enough time to save. Unless I stop the user from reloading.

**Comment by Mezeman1** [comment]
I already save once a minute instead of once every 5 minutes.
