### ISSUE TITLE
Adventure fight gets stuck

### ISSUE THREAD

**Issue by steve2116** [Mezeman1/idle-ant-farm#32]
Not sure exactly how to recreate it. But occasionally, near the start of runs, the enemy would get "stuck" - with their healing always out-healing the ant damage even if the ant damage is over double their healing.

**Comment by Mezeman1** [comment]
Thought I fixed this, are you sure you were on the latest update?

**Comment by steve2116** [comment]
I'll leave another comment if I see it again, but I think so. I don't know how to check what update I'm on though. I'd only had the game open about an hour so I assumed there hadn't been an update since then - unless it doesn't update on loading the game?

**Comment by steve2116** [comment]
Ok I was definitely on an old version. I have to clear all my cookies and cache and log back in again for the game to update. I will reopen the issue if I see the bug again 👍
