### ISSUE TITLE
Seed gathering speed never resets

### ISSUE THREAD

**Issue by Pinkbunnyman** [Mezeman1/idle-ant-farm#4]
Seed gathering speed doesn't reset after buying a queen or prestige. 

Currently have "0/s" displayed, while gathering a few hundred/sec. 

Edit: More testing I just seem to have gotten a base of a couple of hundred per second somehow, it doesn't seem related to current

**Comment by Mezeman1** [comment]
Hmm, that's odd. I've not been able to reproduce this yet. If you know how to reproduce, let me know!

**Comment by Pinkbunnyman** [comment]
It seems to have slowed down and then stopped when I prestiged again.

Guessing it was an improper reset that's been fixed in an update (see video of it happening slowly)

https://github.com/user-attachments/assets/aac68481-3805-49c0-94b1-0b914e3492e7

**Comment by Mezeman1** [comment]
Thank you so much for the video, appreciate it. I've actually found it and fixed it.
