### ISSUE TITLE
Tunnel upgrades are broken

### ISSUE THREAD

**Issue by george-as** [Mezeman1/idle-ant-farm#43]
If you switch to another tab and back to the game several times, the traps in the tunnel will no longer kill any ants and you will find a lot of resources.
![image](https://github.com/user-attachments/assets/45392359-8e9f-4e35-89fe-536959c7dff7)

Probable cause : If you switch to another tab in the browser, and then back to the game, the game state is reloaded. This calls
tunnelStore.loadTunnelState() and it seems to apply the upgrades effects on top of the existing values.
I had "Trap Avoidance" maxed, and after switching tabs 2-3 times the traps stoped killing ants.

**Comment by Mezeman1** [comment]
This might have been fixed

**Comment by svecs132** [comment]
@Mezeman1 you can close this as tunnels are no longer a feature
