### ISSUE TITLE
seeds storage upgrade is more exspensive than seeds pool

### ISSUE THREAD

**Issue by Gerrus89** [Mezeman1/idle-ant-farm#44]
had browser crash due to memory leak in this game. Since that or bit later the seeds storage upgrade is more exspensive than seeds pool, cant reach past 800-900k
[save.txt](https://github.com/user-attachments/files/17241009/save.txt)

**Comment by Mezeman1** [comment]
That's supposed to happen

**Comment by Ivanisdabest14ohyeah** [comment]
ya
so buy storage (the prestige one)
