### ISSUE TITLE
Various tunnel bugs

### ISSUE THREAD

**Issue by localappdata** [Mezeman1/idle-ant-farm#47]
Greetings, here's a list of bugs I found in the tunnels with steps to reproduce and debugging info where available.

- Unable to retrieve anything from the exploration except Mineral Shards (Seeds and Queens aren't retrieved even if no traps are met and the run is successful), which are automatically added to the main interface. Is there a button I'm missing to collect the rest?
- Sending 10 ants will make them invulnerable. They will just keep exploring the tunnels regardless of how many traps they encounter. However, this makes it pretty much the only way to use the tunnels reliably as anything else will kill all ants sent.
- Attempting to upgrade Trap Avoidance at the point of the screenshot throws a silent `Maximum purchases reached for this upgrade.` that appears in console. To reproduce, simply upgrade the skill until this shows up.
- When the run ends, the game throws `Invalid upgrade ID: tunnels` if that is of any help.

Please let me know if you need more information. Thanks!

Attached screenshot of a fearless 10-ant exploration team (those 10 ants don't come back either, by the way) with the Trap Avoidance silently capped skill also shown (button is green but clicking it will throw the above error in console):
![tunnels](https://github.com/user-attachments/assets/020b2c2d-40e2-405a-860e-fd1de06f607c)

**Comment by svecs132** [comment]
hey, i tried working on this issue and i got these results:

1. i was not able to reproduce this issue
2. i was able to reproduce this and i found the probable cause but not a way to fix it yet
3. i have fixed this and its currently in a pull request
4. i have not yet looked into this as it doesnt seem that important

**Comment by svecs132** [comment]
@Mezeman1 you can close this as tunnels are no longer a feature
