### ISSUE TITLE
Queen's Crown stacking (sort of)

### ISSUE THREAD

**Issue by Pinkbunnyman** [Mezeman1/idle-ant-farm#5]
![image](https://github.com/user-attachments/assets/24356c28-770b-4e31-9bef-c3ad6bab476e)
![image](https://github.com/user-attachments/assets/3e6abca7-64ba-47d7-99c1-5f1002bd29b2)

4 queens, 100% more production (that doesn't stack) is 8/sec not 9, if it stacks it should be 16/sec. 

Seems to calculate one properly then added the second.

1 queen: 2/sec
2 queens: 4/sec
3 queens: 7/sec
4 queens: 9/sec

**Comment by Mezeman1** [comment]
Tested this seems to work fine.

Have you considered that it might be because of other prestige upgrades? Maybe you bought a production upgrade?

**Comment by Pinkbunnyman** [comment]
Potentially, I didn't think I bought production boosts when it happened but can't confirm
