### ISSUE TITLE
1st Royal Jelly Can't Use

### ISSUE THREAD

**Issue by drohack** [Mezeman1/idle-ant-farm#52]
Almost always (but not 100%) I can't use the first Royal Jelly. When I click the "Upgrade Ant" button it does nothing. Even when I get a 2nd jelly I can only upgrade the 2nd one and it won't upgrade the 1st.

Sometime when I get the 2nd jelly and click Upgrade Ant it only makes 1 Jelly Ant. Does it cost more than 1 jelly to make a jelly ant? It doesn't say that anywhere... But it doesn't always cost 2 jelly to make an ant. Just occasionally... Really inconsistant.

Why is the "Upgrade Ant" button even a thing. It seems like it just puts in from one count (the 1/infinity) to the "you currently have X Royal Jelly Ants". Why can't I just assign jelly to ants, and not have this middle step?

**Comment by drohack** [comment]
Well I'm guessing this is just another hidden cost. Because on Army Ant, buying a Royal Ant cost 3 Royal Jelly. The game just doesn't tell you that. And the "Upgrade Ant" is still green when you have 1 or 2 Jelly.

**Comment by svecs132** [comment]
hey, i have noticed the button behavior and ive submitted a pull request to the repo with a fix (plus making the button show the cost)

also yes, the cost changes in every evolution, here are the costs (royal jelly per royal jelly ant) i found in the code:

ants: 2.5
leafcutter ants: 1
fire ants: 2
harvester ants: 1.5
army ants: 3
weaver ants: 2.5
desert ants: 3
bullet ants: 3.5
carpenter ants: 4

note: the cost could change throughout updates but this is the current state
