### ISSUE TITLE
storage ants not working(fixed)

### ISSUE THREAD

**Issue by izeekomni** [Mezeman1/idle-ant-farm#62]
Ants

Ants collect seeds and fight bugs.

Count: 1.46K/1.00K (146.4%) 

edit: is just a visual bug from the max because if i stop increasing housing it stops creating ants
edit: typo: 
Wasp Stinger

Increases army attack by attack by 20% for 5 minutes.

**Comment by Mezeman1** [comment]
Should have been fixed!
