### ISSUE TITLE
BUG: seeds (or equivalent resources) may go above 100%

### ISSUE THREAD

**Issue by svecs132** [Mezeman1/idle-ant-farm#67]
while the user is holding the collect button, seeds may go above 100% for around a second before getting reset to the maximum amount and that repeats as long as the user holds the button or just keeps their mouse over it

[https://ctrlv.tv/T4XP](https://ctrlv.tv/T4XP)

**Comment by Mezeman1** [comment]
Ya, don't really care about this to be honest.
