### ISSUE TITLE
Text selection QoL

### ISSUE THREAD

**Issue by steve2116** [Mezeman1/idle-ant-farm#7]
Currently you can select the text (and also entire buttons). This isn't very ideal when on mobile and trying to click the same thing multiple times it selects the text instead of clicking.

Just a small quality of life, nothing major. It might be better to leave it as it is and keep being able to select the text.

For context it was when I was pressing to upgrade larvae storage.

(also sorry about making so many issues lmao 😅)

**Comment by Mezeman1** [comment]
No, I'm actually glad you're doing it! Thanks man. :) I'll look into it. Probably just buttons shouldn't be text selectable.

**Comment by Mezeman1** [comment]
All buttons now have the user-select: none; property
