### ISSUE TITLE
Royal Jelly - Press to buy

### ISSUE THREAD

**Issue by Quetzalicious** [Mezeman1/idle-ant-farm#70]
With potentially having to click a few 1000 times down the road, I'd like to suggest a QoL feature.

![](https://github.com/user-attachments/assets/815ed9ec-5d2d-4c10-b599-551be1a5a628)

I'd appreciate it if the "Upgrade Ant", and the '+' and '-' buttons for each type would behave like the resource "Hold to collect"-button.  
Optionally, this button could speed up buying the type the longer it is pressed.  Since it's possible to decrease as well as increase, it matters little if players overshoot a target due to this speed-up.

**Comment by localappdata** [comment]
Alternately, a "Max" button would also solve the massive clicking issue without clogging up the UI too much. Click Max once, convert all available Royal Jelly to Royal Jelly Ants and max out all workers/soldiers/royal queens to the limit of your available RJA.

Edit: Somehow missed this one, thanks svecs!

**Comment by svecs132** [comment]
@localappdata #65
