### ISSUE TITLE
Suggestion - Buy max for prestige upgrades

### ISSUE THREAD

**Issue by steve2116** [Mezeman1/idle-ant-farm#8]
Upgrades might change how they work, and it's only really an issue for later on. But I have to click about 20 times on each upgrade each prestige.

Similarly a buy max for upgrading larvae storage (or an autobuyer) would be nice.

(I'm back at it 😅)

**Comment by Mezeman1** [comment]
Autobuyer for larvea has been removed to give more meaning to the queens. Storage autobuy will be added for sure.
