### ISSUE TITLE
Suggestion - different formats for numbers

### ISSUE THREAD

**Issue by steve2116** [Mezeman1/idle-ant-farm#9]
Currently numbers are shown as scientific. It would be nice to show them as engineering (eg 24e+12) or have letters past million (eg 24t)

**Comment by Mezeman1** [comment]
Going to be a setting in settings menu, where you can choose. For now it's going to stay as is.

**Comment by TheInterester-school** [comment]
branching off of this--extra decimal places. currently accuracy is only to ones/one sigfig, which can be a little confusing at lower values where it can appear that production upgrades aren't working. Adding a setting to have more/defaulting to showing 2 decimal places could be helpful.

**Comment by Mezeman1** [comment]
> branching off of this--extra decimal places. currently accuracy is only to ones/one sigfig, which can be a little confusing at lower values where it can appear that production upgrades aren't working. Adding a setting to have more/defaulting to showing 2 decimal places could be helpful.

Has been fixed
